export const ACTION_TYPES = {
    
    ALL_PRODUCTS_REQUEST: 'ALL_PRODUCTS_REQUEST',
    ALL_PRODUCTS_SUCCESS: 'ALL_PRODUCTS_SUCCESS',
    ALL_PRODUCTS_FAIL: 'ALL_PRODUCTS_FAIL',

    GET_PRODUCT_DETAILS_REQUEST: 'GET_PRODUCT_DETAILS_REQUEST',
    GET_PRODUCT_DETAILS_SUCCESS: 'GET_PRODUCT_DETAILS_SUCCESS',
    GET_PRODUCT_DETAILS_FAIL: 'GET_PRODUCT_DETAILS_FAIL',
  
    UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',  
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_RESET: 'UPDATE_PRODUCT_RESET',
    UPDATE_PRODUCT_FAIL: 'UPDATE_PRODUCT_FAIL',
  
    NEW_PRODUCT_REQUEST: 'NEW_PRODUCT_REQUEST',  
    NEW_PRODUCT_SUCCESS: 'NEW_PRODUCT_SUCCESS',
    NEW_PRODUCT_RESET: 'NEW_PRODUCT_RESET',
    NEW_PRODUCT_FAIL: 'NEW_PRODUCT_FAIL',
  
    DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_RESET: 'DELETE_PRODUCT_RESET',
    DELETE_PRODUCT_FAIL: 'DELETE_PRODUCT_FAIL',

    CLEAR_ERRORS: 'CLEAR_ERRORS'
}


